apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pet.fullname" . }}-web
  labels:
    {{- include "pet.labels" . | nindent 4 }}
    {{- include "pet.web.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "pet.web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pet.web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
