apiVersion: v2
name: pet
description: Practice Efficiency Tracking — v2 Helm Chart
type: application
version: 0.1.0
appVersion: "2.0.0"

dependencies:
  - name: postgresql
    version: "16.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
